C++ has call-by-value semantics, but you can pass a reference to a function.  Fortran has call by reference, but you can specify call-by-value by annotating a dummy variable with `value`.

What is the deal for Julia?

# Basic type arguments

Consider the following function:

In [1]:
function swap(x, y)
    tmp = x
    x = y
    y = tmp
    return
end

swap (generic function with 1 method)

If Julia supports call-by-reference, then if we call it with variables as arguments, their values would be swapped in the calling context.

In [2]:
a = 3; b = 5;
swap(a, b)
a, b

(3, 5)

Clearly, `a` and `b` retain their values in the calling context, so Julia uses call-by-value semantics.

# Data structure arguments

However, we can modify a value that is a data structure, for instance the components of a vector.

In [13]:
function iota(v::Vector{<:Number}, start::Number)
    for i in 1:length(v)
        v[i] = start + (i - 1)
    end
    return v
end

iota (generic function with 2 methods)

In [14]:
x = Array{Int64}(undef, 10);

In [15]:
iota(x, 5)

10-element Vector{Int64}:
  5
  6
  7
  8
  9
 10
 11
 12
 13
 14

In [17]:
x

10-element Vector{Int64}:
  5
  6
  7
  8
  9
 10
 11
 12
 13
 14

Clearly, we were able to modify the *components* of the `Vector` that was passed of an argument.  However, we can not modify the actual value being passed in, i.e., calling the `swap` function with two `Vector`s as arguments will not change the arguments.

In [19]:
y = zeros(Int64, 1, 10)

1×10 Matrix{Int64}:
 0  0  0  0  0  0  0  0  0  0

In [20]:
swap(x, y)

In [22]:
x, y

([5, 6, 7, 8, 9, 10, 11, 12, 13, 14], [0 0 … 0 0])